### ISSUE TITLE
error message when sending to NewKaku with id of 8 chars

### ISSUE THREAD

**Issue by FrankVaes** [cyrilcc/org.openhab.binding.rflink#23] opened 2018-03-04 12:36 UTC
Hello Cyril

i have the binding working. i was trying to control a NewKaku device. It is discoverd by the binding. Status of the command is coming in to openhab. But when i try to give a command i get the following error.

-------
2018-03-04 13:25:38.463 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rflink.handler.RfLinkHandler@b870b0': String index out of range: -2
--------

When i remove the first 2 zero's of the id, like from, NewKaku-0083ce0a-c => NewKaku-83ce0a-c. Send command is working fine. when i then press the original switch openhab changes the id back to NewKaku-0083ce0a-c.

I tried to make a manual thing and give it the id NewKaku-83ce0a-c. then the id is not changed anymore. this works for the sending part, but i dont recieve update from the original switch.

i can make an widget with the status of one thing and the command to the other. but this is far from ideal. can you help me?

greetings Frank Vaes

**Comment by johnjore** [comment] 2018-03-04 16:43
Hi!

I can try and take a look. No promises.

Enable debug logging (remove noise from other bindings), send and receive a few times, and I might be able to figure out what the problem is.

Also share your things setup for a relevant device and I'll add it to my setup to test with.

Only a limited amount of testing was done for sending commands, and only for devices I have so I'm not surprised some protocols don't work without a bit of tuning.

I am here assuming the rflink protocol is actually called newkaku...



JJ

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by FrankVaes** [comment] 2018-03-04 17:50
i have tried to ad te debug rule, but not shure it is working. the log i have is:

2018-03-04 18:48:14.488 [ome.event.ItemCommandEvent] - Item 'KamerKimLinks_Command' received command ON

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:14.493 [WARN ] [g.rflink.handler.RfLinkBridgeHandler] - sendMessage: Raw data = unknown, Command = ON, Contact = CLOSED

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:14.500 [vent.ItemStateChangedEvent] - KamerKimLinks_Command changed from OFF to ON

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:14.498 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rflink.handler.RfLinkHandler@10cdf0d': String index out of range: -2

java.lang.StringIndexOutOfBoundsException: String index out of range: -2

	at java.lang.String.substring(String.java:1931) [?:?]

	at org.openhab.binding.rflink.messages.RfLinkBaseMessage.decodeMessage(RfLinkBaseMessage.java:161) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.messages.RfLinkSwitchMessage.decodeMessage(RfLinkSwitchMessage.java:205) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.send(RfLinkBridgeHandler.java:79) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.enqueue(RfLinkBridgeHandler.java:68) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler.sendMessage(RfLinkBridgeHandler.java:165) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkHandler.handleCommand(RfLinkHandler.java:63) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at com.sun.proxy.$Proxy129.handleCommand(Unknown Source) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:15.896 [ome.event.ItemCommandEvent] - Item 'KamerKimLinks_Command' received command OFF

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:15.904 [WARN ] [g.rflink.handler.RfLinkBridgeHandler] - sendMessage: Raw data = unknown, Command = OFF, Contact = CLOSED

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:15.914 [vent.ItemStateChangedEvent] - KamerKimLinks_Command changed from ON to OFF

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:15.909 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rflink.handler.RfLinkHandler@10cdf0d': String index out of range: -2

java.lang.StringIndexOutOfBoundsException: String index out of range: -2

	at java.lang.String.substring(String.java:1931) [?:?]

	at org.openhab.binding.rflink.messages.RfLinkBaseMessage.decodeMessage(RfLinkBaseMessage.java:161) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.messages.RfLinkSwitchMessage.decodeMessage(RfLinkSwitchMessage.java:205) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.send(RfLinkBridgeHandler.java:79) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.enqueue(RfLinkBridgeHandler.java:68) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler.sendMessage(RfLinkBridgeHandler.java:165) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkHandler.handleCommand(RfLinkHandler.java:63) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at com.sun.proxy.$Proxy129.handleCommand(Unknown Source) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:17.241 [ome.event.ItemCommandEvent] - Item 'KamerKimLinks_Command' received command ON

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:17.247 [WARN ] [g.rflink.handler.RfLinkBridgeHandler] - sendMessage: Raw data = unknown, Command = ON, Contact = CLOSED

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:17.251 [vent.ItemStateChangedEvent] - KamerKimLinks_Command changed from OFF to ON

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:17.250 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rflink.handler.RfLinkHandler@10cdf0d': String index out of range: -2

java.lang.StringIndexOutOfBoundsException: String index out of range: -2

	at java.lang.String.substring(String.java:1931) [?:?]

	at org.openhab.binding.rflink.messages.RfLinkBaseMessage.decodeMessage(RfLinkBaseMessage.java:161) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.messages.RfLinkSwitchMessage.decodeMessage(RfLinkSwitchMessage.java:205) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.send(RfLinkBridgeHandler.java:79) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.enqueue(RfLinkBridgeHandler.java:68) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler.sendMessage(RfLinkBridgeHandler.java:165) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkHandler.handleCommand(RfLinkHandler.java:63) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at com.sun.proxy.$Proxy129.handleCommand(Unknown Source) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:18.432 [ome.event.ItemCommandEvent] - Item 'KamerKimLinks_Command' received command OFF

==> /var/log/openhab2/openhab.log <==

2018-03-04 18:48:18.438 [WARN ] [g.rflink.handler.RfLinkBridgeHandler] - sendMessage: Raw data = unknown, Command = OFF, Contact = CLOSED

2018-03-04 18:48:18.450 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rflink.handler.RfLinkHandler@10cdf0d': String index out of range: -2

java.lang.StringIndexOutOfBoundsException: String index out of range: -2

	at java.lang.String.substring(String.java:1931) [?:?]

	at org.openhab.binding.rflink.messages.RfLinkBaseMessage.decodeMessage(RfLinkBaseMessage.java:161) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.messages.RfLinkSwitchMessage.decodeMessage(RfLinkSwitchMessage.java:205) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.send(RfLinkBridgeHandler.java:79) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.enqueue(RfLinkBridgeHandler.java:68) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkBridgeHandler.sendMessage(RfLinkBridgeHandler.java:165) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.openhab.binding.rflink.handler.RfLinkHandler.handleCommand(RfLinkHandler.java:63) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at com.sun.proxy.$Proxy129.handleCommand(Unknown Source) [202:org.openhab.binding.rflink:2.2.0.201802251956]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==

2018-03-04 18:48:18.471 [vent.ItemStateChangedEvent] - KamerKimLinks_Command changed from ON to OFF

**Comment by FrankVaes** [comment] 2018-03-04 17:52
thing configuration is:

![image](https://user-images.githubusercontent.com/36824355/36948579-30015402-1fdd-11e8-8ecc-36d51a63ffb8.png)

![image](https://user-images.githubusercontent.com/36824355/36948582-3da7481e-1fdd-11e8-958c-f3a4b31608bd.png)

**Comment by johnjore** [comment] 2018-03-04 19:13
Hm.. no, please create the thing file as per the instructions in the readme.md file, this is important for devices you control. For temp sensors and other inbound only, it does not matter.
To send a command, the thing needs a specific format that I’m not sure is being followed based on the screenshot. The correct format is explained in the readme.md file.

For the log file, debug is not enabled. Please don’t try and align the two files events.log and openhab.log… makes it much harder for me to read…
If debug is enabled there will be lines with “>>>” and “<<<” showing the communication commands with the RfLink device.

I suspect the root cause is that the “thing” is not defined correctly. Once this is done correctly, the problems should hopefully go away.


JJ

**Comment by FrankVaes** [comment] 2018-03-04 19:24
hello,

i will give it a try in getting the data you need. but i am not that comfortable with OH2 or a raspberry or linux. i don't know if a teamviewer session is ok for you? is maybe the most quick and easy way for both.

But i shall try to collect the data.

thanks for the effort.

**Comment by johnjore** [comment] 2018-03-04 19:27
No, I don't have time, or the energy, to provide personal support. Use Windows if you're not comfortable with Linux. Your favorite search engine should also be able to provide a lot of answers.

**Comment by FrankVaes** [comment] 2018-03-04 19:34
i am going to give it a try. i can understand youre oppinion, was just an option nothing more. i will get back with the files.

**Comment by FrankVaes** [comment] 2018-03-04 20:21
sorry for the logfile earlier, that was a copy from the webinterface of the OH log.  i have attachted a part of the openhab.log. 

i am trying to get the debug in the log file. but i don't get the >>> in the file. (still trying).

i have the things declared via OH, when i auto add (via inbox), the id = 0083ce0a. the recieving works and not the sending. When i declare a new thing in OH (not via file) with a slightly different id number (6 digits as in the readme.md) i just deleted the first 2 zero's (83ce0a). then the sending works and not the recieving.

I hope this helps. i am going to get the rest of the files for you ( i am going to ask a friend to help me with this, this will take a few days). but this is wat i figured out.

i am very keen in solving this because this was the mean reason i bought the RFlink, sorry if i am over enthusiastic. 

[log.txt](https://github.com/cyrilcc/org.openhab.binding.rflink/files/1778888/log.txt)

**Comment by FrankVaes** [comment] 2018-03-05 16:19
i have extracted the config of the thing from the json file. hope this is what you mean. i did not manage to get the logging working jet. still trying. the config is attached.

[json config thing.txt](https://github.com/cyrilcc/org.openhab.binding.rflink/files/1781663/json.config.thing.txt)

**Comment by FrankVaes** [comment] 2018-03-13 21:14
i think i managed to set the logging to debug. but i am nog getting >>> in the log file. i am getting DEBUG rules in the logging. i have attached the logging, hopefully it helps in solving the problem.

thanks in advance.
[logging.txt](https://github.com/cyrilcc/org.openhab.binding.rflink/files/1808684/logging.txt)

**Comment by johnjore** [comment] 2018-03-14 08:12
From what I can see, you have not defined the "thing" correctly. Please re-read the readme.md file and create the things file manually (Search OpenHAB forum for help on how to do this if you are unsure), and make sure you follow the examples given. Best to just copy and paste one of them into your configuration and see it communicates with the RfLink. It does not matter that you dont have a device of that specific type or ID, its just to confirm it works. Then add your device, in the exact same way...


JJ

**Comment by FrankVaes** [comment] 2018-03-14 08:55
How can i define the thing wrongly, when it is automatically added via the inbox?

I shall give it a try by manually defining a thing file. but it seems to me this should be working via the inbox.

I did change the id to 6 figures and than the sending works (as i stated before). but then the receiving of the signal of the original switch does not work (by a thing manually added through paperui). when the thing is automatically added and i change the id, the sending does also work. but when i then press the switch the id is automatically changed again and sending stops working.

**Comment by FrankVaes** [comment] 2018-03-14 09:08
am i very wrong when i think the binding has to be able to send a string of 8 char to the rf link in stead of a maximum of 6?

**Comment by FrankVaes** [comment] 2018-04-05 14:38
ok, that sounds great. can i get youre local copy to test?

**Comment by FrankVaes** [comment] 2018-04-30 09:34
please help me solve this issue.

**Comment by cartemere** [comment] 2019-02-20 19:03
Devices with Id length = 8 char are correctly supported thanks to @johnjore commit.
I close the issue

**Closed by cartemere** 2019-02-20 19:03 UTC
